### ISSUE TITLE
Bugs, Issues, and Feature Suggestions for PicPeak

### ISSUE THREAD

**Issue by maximilianbiebl** [the-luap/picpeak#14]
I have encountered several issues with my installation and also have some suggestions for improvements:

1. **Gallery Download Button:**
   When selecting images for download in the gallery, the button shows `{{count}} ausgewählte herunterladen`.

2. **Filter Function:**
   It would be nice to filter images so that only those that are marked or liked are displayed.

3. **Guest Image Upload:**
   Uploading images via the gallery as a guest does not work for me. The error always appears: `"no token provided"`.

4. **Moderating Comments:**
   Comments appear in the dashboard for moderation. However, clicking the `"Approve | Hide | Delete"` buttons has no effect.

5. **Upload via Admin Dashboard:**
   Uploading images via the admin dashboard only works for files smaller than 1 MB. The following error appears:

   ```
   [error] 30#30: *322 client intended to send too large body: 3622278 bytes
   ```

   This occurs even though the nginx configuration sets `client_max_body_size 0;` (unlimited). Changing this value does not resolve the issue.

6. **Login via Reverse Proxy:**
   I can access PicPeak via the server name or IP address. However, logging in through the reverse proxy fails. Accessing the dashboard and gallery via the domain from outside the network works, but logging in to either the gallery or dashboard results in:

   ```
   Request Method: POST; Status Code: 500 Internal Server Error
   ```

   This issue is described on GitHub as:
   *"This is the most common deployment issue! Usually caused by misconfigured URLs or network problems."*
   I have adjusted `server.js` (CORS section) as well as `backend.env` and `.env` in the main directory.
   I have tried with and without ports—unfortunately without success. The documentation and example.env are contradictory regarding which ports should be used, or whether ports need to be used at all.

7. **Gallery Share Link:**
   Clicking `"COPY"` for the gallery share link in the dashboard results in the error: `"Something went wrong"`.

8. **Gallery View Customization:**
   It would be nice to be able to adjust or personalize the PicPeak logo in the gallery view, which is currently very large and centered.

9. **Adding Images from Other Folders/Drives:**
   It would be practical to add images from other folders or drives of the event, so that images do not have to be uploaded to PicPeak but can also include files already present on the server.

**System:**
I have installed PicPeak on my Synology using Docker.

**Comment by orderedstereographic** [comment]
Hi, I think I've struggled with some of the same issues in my attempt to deploy today so guests can share photos. I have a custom networking setup for my various stacks, so I'm very opposed to directly exposing ports within a compose.

For point 6: I stumbled into a solution by using a separate domain for the backend and making sure that the backend is listening on 3001.

For point 5, I've gotten around the issue in a very hacky way by ad-hoc modifying the image to change the internal nginx config. Unfortunately, I immediately run into point 3.

Here's some relevant portions of my config:

`compose.yaml`
```
  frontend:
    container_name: picpeak-frontend
    build:
      dockerfile_inline: >
        FROM ghcr.io/the-luap/picpeak/frontend:latest

        USER root

        RUN sed -i '/index index.html;/aclient_max_body_size 128M;\nclient_body_timeout 2m;' /etc/nginx/conf.d/default.conf

        USER nginx
    environment:
      - VITE_API_URL=/api
    ...
```

`.env`
```
FRONTEND_URL=https://frontend.example.com
ADMIN_URL=https://backend.example.com
VITE_API_URL=https://backend.example.com

BACKEND_PORT=3001
FRONTEND_PORT=80

# Possibly the backend needs this variable name instead.
PORT=3001
```

**Comment by maximilianbiebl** [comment]
Thanks, your configuration helped!

```
FRONTEND_URL=https://domain.example.com
ADMIN_URL=https://domain.example.com
VITE_API_URL=https://domain.example.com

BACKEND_PORT=3001
FRONTEND_PORT=80

# Possibly the backend needs this variable name instead.
PORT=3001
```

Using these port variables solved the **500 Internal Server Error** for me as well, and it was not necessary to use a separate backend domain.

To quickly test the upload issue without rebuilding the Docker image, I executed the following command via SSH:

```
sed -i '/index index.html;/aclient_max_body_size 128M;\nclient_body_timeout 2m;' /etc/nginx/conf.d/default.conf
```

This also worked — uploading images via the dashboard now functions correctly, and the gallery link "COPY" feature is working too.

Regarding the `"no token provided"` error, I noticed that the actual response is:

```
Status Code: 401 Unauthorized
```

So for me, points **5, 6, and 7** are now resolved.

**Comment by the-luap** [comment]
@maximilianbiebl can you please open feature requests for items 8 & 9?
all other items are fixed now

**Comment by maximilianbiebl** [comment]
I still have this Problem: 
Gallery Download Button:
When selecting images for download in the gallery, the button shows `{{count}} ausgewählte herunterladen.`

<img width="296" height="165" alt="Image" src="https://github.com/user-attachments/assets/a8db800e-4e22-483b-8de0-939d86b68f8f" />
