### ISSUE TITLE
[BUG] Session issues, missing gallery favorite button, guest feedback option not saved, external sources not selectable

### ISSUE THREAD

**Issue by maximilianbiebl** [the-luap/picpeak#29]
**Description:**
After the latest update I noticed several issues:

1. **Session/Login**
   When the gallery page is reloaded (either manually or automatically after uploading an image), I need to log in again.

2. **Favorite function**
   In the settings and gallery filters, the option to mark images as favorites is still available. However, the button to actually mark an image as favorite is missing in the gallery view, making the feature unusable.

3. **Guest feedback**
   When creating an event and enabling the option *Allow guest feedback*, it is not saved — after the event is created, the option is no longer selected.

4. **External sources**
   I can see the menu entry to reference external sources, but I cannot click *Select* to enable the function — even though my configuration is correctly set.

   One question: If external sources are enabled, can I only use images from that external source, or is it still possible to also upload images directly via PicPeak?

**System/Setup:**
Synology + Docker

**Comment by the-luap** [comment]
the last commit should fix the problems from 1-3.
For issue 4, the external sources should work with current version. There is the import from external folder button within the gallery, there you can go to the folder you want to select to import the images from, click on select for selecting the path and then use the import button on the popup to import all pictures from the folder. Currently it does not support partial import.
About the external source yes it is still possible to upload images if you use external sources.

**Comment by maximilianbiebl** [comment]
Great, it’s working now! However, I still have an issue with the external folders:

* My external source contains **63 images**.
* The same number of thumbnails (**63**) is correctly generated in the PicPeak `thumbnails` folder.
* But in the gallery I see **371 images** — the same pictures appear multiple times in **different sizes**.

So it seems like the external images are being duplicated in the gallery view with multiple size variations.

**Comment by maximilianbiebl** [comment]
Great it's working now, thanks a lot
